# Generated by Django 3.2.4 on 2021-07-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('nogizaka', '乃木坂46'), ('hinatazaka', '日向坂46'), ('sakurazaka', '櫻坂46')], max_length=50, verbose_name='カテゴリ'),
        ),
    ]
